-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.11.0.396.4
-- Module  Version: 7.5
-- Tue Jan 12 13:04:37 2021

-- parameterized module component declaration
component Outputbuffer
    port (DataInA: in  std_logic_vector(29 downto 0); 
        DataInB: in  std_logic_vector(119 downto 0); 
        AddressA: in  std_logic_vector(9 downto 0); 
        AddressB: in  std_logic_vector(7 downto 0); 
        ClockA: in  std_logic; ClockB: in  std_logic; 
        ClockEnA: in  std_logic; ClockEnB: in  std_logic; 
        WrA: in  std_logic; WrB: in  std_logic; ResetA: in  std_logic; 
        ResetB: in  std_logic; QA: out  std_logic_vector(29 downto 0); 
        QB: out  std_logic_vector(119 downto 0));
end component;

-- parameterized module component instance
__ : Outputbuffer
    port map (DataInA(29 downto 0)=>__, DataInB(119 downto 0)=>__, 
        AddressA(9 downto 0)=>__, AddressB(7 downto 0)=>__, ClockA=>__, 
        ClockB=>__, ClockEnA=>__, ClockEnB=>__, WrA=>__, WrB=>__, ResetA=>__, 
        ResetB=>__, QA(29 downto 0)=>__, QB(119 downto 0)=>__);
