/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 6.5 */
/* C:/lscc/diamond/3.11_x64/ispfpga/bin/nt64/scuba -w -bus_exp 7 -bb -arch xo3c00f -type bram -wp 10 -rp 0011 -data_width 55 -num_rows 1024 -rdata_width 55 -read_reg1 outreg -gsr DISABLED -memformat bin -cascade -1 -n pmi_ram_dpXbnonesadr55101024551010241218d42b -pmi -lang verilog  */
/* Wed Jan 06 01:26:09 2021 */


`timescale 1 ns / 1 ps
module pmi_ram_dpXbnonesadr55101024551010241218d42b (WrAddress, 
    RdAddress, Data, WE, RdClock, RdClockEn, Reset, WrClock, WrClockEn, 
    Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [9:0] WrAddress;
    input wire [9:0] RdAddress;
    input wire [54:0] Data;
    input wire WE;
    input wire RdClock;
    input wire RdClockEn;
    input wire Reset;
    input wire WrClock;
    input wire WrClockEn;
    output wire [54:0] Q;

    wire scuba_vhi;
    wire scuba_vlo;

    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_0_6.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_0_6.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_0_6.CSDECODE_B = "0b000" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_0_6.CSDECODE_A = "0b000" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_0_6.WRITEMODE_B = "NORMAL" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_0_6.WRITEMODE_A = "NORMAL" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_0_6.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_0_6.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_0_6.REGMODE_B = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_0_6.REGMODE_A = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_0_6.DATA_WIDTH_B = 9 ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_0_6.DATA_WIDTH_A = 9 ;
    DP8KC pmi_ram_dpXbnonesadr55101024551010241218d42b_0_0_6 (.DIA8(Data[8]), 
        .DIA7(Data[7]), .DIA6(Data[6]), .DIA5(Data[5]), .DIA4(Data[4]), 
        .DIA3(Data[3]), .DIA2(Data[2]), .DIA1(Data[1]), .DIA0(Data[0]), 
        .ADA12(WrAddress[9]), .ADA11(WrAddress[8]), .ADA10(WrAddress[7]), 
        .ADA9(WrAddress[6]), .ADA8(WrAddress[5]), .ADA7(WrAddress[4]), .ADA6(WrAddress[3]), 
        .ADA5(WrAddress[2]), .ADA4(WrAddress[1]), .ADA3(WrAddress[0]), .ADA2(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA0(scuba_vhi), .CEA(WrClockEn), .OCEA(WrClockEn), 
        .CLKA(WrClock), .WEA(WE), .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), 
        .RSTA(Reset), .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB0(scuba_vlo), .ADB12(RdAddress[9]), .ADB11(RdAddress[8]), 
        .ADB10(RdAddress[7]), .ADB9(RdAddress[6]), .ADB8(RdAddress[5]), 
        .ADB7(RdAddress[4]), .ADB6(RdAddress[3]), .ADB5(RdAddress[2]), .ADB4(RdAddress[1]), 
        .ADB3(RdAddress[0]), .ADB2(scuba_vlo), .ADB1(scuba_vlo), .ADB0(scuba_vlo), 
        .CEB(RdClockEn), .OCEB(RdClockEn), .CLKB(RdClock), .WEB(scuba_vlo), 
        .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), 
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), 
        .DOA0(), .DOB8(Q[8]), .DOB7(Q[7]), .DOB6(Q[6]), .DOB5(Q[5]), .DOB4(Q[4]), 
        .DOB3(Q[3]), .DOB2(Q[2]), .DOB1(Q[1]), .DOB0(Q[0]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr55101024551010241218d42b__PMIP__1024__55__55B" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_1_5.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_1_5.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_1_5.CSDECODE_B = "0b000" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_1_5.CSDECODE_A = "0b000" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_1_5.WRITEMODE_B = "NORMAL" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_1_5.WRITEMODE_A = "NORMAL" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_1_5.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_1_5.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_1_5.REGMODE_B = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_1_5.REGMODE_A = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_1_5.DATA_WIDTH_B = 9 ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_1_5.DATA_WIDTH_A = 9 ;
    DP8KC pmi_ram_dpXbnonesadr55101024551010241218d42b_0_1_5 (.DIA8(Data[17]), 
        .DIA7(Data[16]), .DIA6(Data[15]), .DIA5(Data[14]), .DIA4(Data[13]), 
        .DIA3(Data[12]), .DIA2(Data[11]), .DIA1(Data[10]), .DIA0(Data[9]), 
        .ADA12(WrAddress[9]), .ADA11(WrAddress[8]), .ADA10(WrAddress[7]), 
        .ADA9(WrAddress[6]), .ADA8(WrAddress[5]), .ADA7(WrAddress[4]), .ADA6(WrAddress[3]), 
        .ADA5(WrAddress[2]), .ADA4(WrAddress[1]), .ADA3(WrAddress[0]), .ADA2(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA0(scuba_vhi), .CEA(WrClockEn), .OCEA(WrClockEn), 
        .CLKA(WrClock), .WEA(WE), .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), 
        .RSTA(Reset), .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB0(scuba_vlo), .ADB12(RdAddress[9]), .ADB11(RdAddress[8]), 
        .ADB10(RdAddress[7]), .ADB9(RdAddress[6]), .ADB8(RdAddress[5]), 
        .ADB7(RdAddress[4]), .ADB6(RdAddress[3]), .ADB5(RdAddress[2]), .ADB4(RdAddress[1]), 
        .ADB3(RdAddress[0]), .ADB2(scuba_vlo), .ADB1(scuba_vlo), .ADB0(scuba_vlo), 
        .CEB(RdClockEn), .OCEB(RdClockEn), .CLKB(RdClock), .WEB(scuba_vlo), 
        .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), 
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), 
        .DOA0(), .DOB8(Q[17]), .DOB7(Q[16]), .DOB6(Q[15]), .DOB5(Q[14]), 
        .DOB4(Q[13]), .DOB3(Q[12]), .DOB2(Q[11]), .DOB1(Q[10]), .DOB0(Q[9]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr55101024551010241218d42b__PMIP__1024__55__55B" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_2_4.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_2_4.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_2_4.CSDECODE_B = "0b000" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_2_4.CSDECODE_A = "0b000" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_2_4.WRITEMODE_B = "NORMAL" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_2_4.WRITEMODE_A = "NORMAL" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_2_4.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_2_4.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_2_4.REGMODE_B = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_2_4.REGMODE_A = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_2_4.DATA_WIDTH_B = 9 ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_2_4.DATA_WIDTH_A = 9 ;
    DP8KC pmi_ram_dpXbnonesadr55101024551010241218d42b_0_2_4 (.DIA8(Data[26]), 
        .DIA7(Data[25]), .DIA6(Data[24]), .DIA5(Data[23]), .DIA4(Data[22]), 
        .DIA3(Data[21]), .DIA2(Data[20]), .DIA1(Data[19]), .DIA0(Data[18]), 
        .ADA12(WrAddress[9]), .ADA11(WrAddress[8]), .ADA10(WrAddress[7]), 
        .ADA9(WrAddress[6]), .ADA8(WrAddress[5]), .ADA7(WrAddress[4]), .ADA6(WrAddress[3]), 
        .ADA5(WrAddress[2]), .ADA4(WrAddress[1]), .ADA3(WrAddress[0]), .ADA2(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA0(scuba_vhi), .CEA(WrClockEn), .OCEA(WrClockEn), 
        .CLKA(WrClock), .WEA(WE), .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), 
        .RSTA(Reset), .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB0(scuba_vlo), .ADB12(RdAddress[9]), .ADB11(RdAddress[8]), 
        .ADB10(RdAddress[7]), .ADB9(RdAddress[6]), .ADB8(RdAddress[5]), 
        .ADB7(RdAddress[4]), .ADB6(RdAddress[3]), .ADB5(RdAddress[2]), .ADB4(RdAddress[1]), 
        .ADB3(RdAddress[0]), .ADB2(scuba_vlo), .ADB1(scuba_vlo), .ADB0(scuba_vlo), 
        .CEB(RdClockEn), .OCEB(RdClockEn), .CLKB(RdClock), .WEB(scuba_vlo), 
        .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), 
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), 
        .DOA0(), .DOB8(Q[26]), .DOB7(Q[25]), .DOB6(Q[24]), .DOB5(Q[23]), 
        .DOB4(Q[22]), .DOB3(Q[21]), .DOB2(Q[20]), .DOB1(Q[19]), .DOB0(Q[18]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr55101024551010241218d42b__PMIP__1024__55__55B" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_3_3.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_3_3.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_3_3.CSDECODE_B = "0b000" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_3_3.CSDECODE_A = "0b000" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_3_3.WRITEMODE_B = "NORMAL" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_3_3.WRITEMODE_A = "NORMAL" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_3_3.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_3_3.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_3_3.REGMODE_B = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_3_3.REGMODE_A = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_3_3.DATA_WIDTH_B = 9 ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_3_3.DATA_WIDTH_A = 9 ;
    DP8KC pmi_ram_dpXbnonesadr55101024551010241218d42b_0_3_3 (.DIA8(Data[35]), 
        .DIA7(Data[34]), .DIA6(Data[33]), .DIA5(Data[32]), .DIA4(Data[31]), 
        .DIA3(Data[30]), .DIA2(Data[29]), .DIA1(Data[28]), .DIA0(Data[27]), 
        .ADA12(WrAddress[9]), .ADA11(WrAddress[8]), .ADA10(WrAddress[7]), 
        .ADA9(WrAddress[6]), .ADA8(WrAddress[5]), .ADA7(WrAddress[4]), .ADA6(WrAddress[3]), 
        .ADA5(WrAddress[2]), .ADA4(WrAddress[1]), .ADA3(WrAddress[0]), .ADA2(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA0(scuba_vhi), .CEA(WrClockEn), .OCEA(WrClockEn), 
        .CLKA(WrClock), .WEA(WE), .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), 
        .RSTA(Reset), .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB0(scuba_vlo), .ADB12(RdAddress[9]), .ADB11(RdAddress[8]), 
        .ADB10(RdAddress[7]), .ADB9(RdAddress[6]), .ADB8(RdAddress[5]), 
        .ADB7(RdAddress[4]), .ADB6(RdAddress[3]), .ADB5(RdAddress[2]), .ADB4(RdAddress[1]), 
        .ADB3(RdAddress[0]), .ADB2(scuba_vlo), .ADB1(scuba_vlo), .ADB0(scuba_vlo), 
        .CEB(RdClockEn), .OCEB(RdClockEn), .CLKB(RdClock), .WEB(scuba_vlo), 
        .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), 
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), 
        .DOA0(), .DOB8(Q[35]), .DOB7(Q[34]), .DOB6(Q[33]), .DOB5(Q[32]), 
        .DOB4(Q[31]), .DOB3(Q[30]), .DOB2(Q[29]), .DOB1(Q[28]), .DOB0(Q[27]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr55101024551010241218d42b__PMIP__1024__55__55B" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_4_2.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_4_2.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_4_2.CSDECODE_B = "0b000" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_4_2.CSDECODE_A = "0b000" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_4_2.WRITEMODE_B = "NORMAL" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_4_2.WRITEMODE_A = "NORMAL" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_4_2.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_4_2.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_4_2.REGMODE_B = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_4_2.REGMODE_A = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_4_2.DATA_WIDTH_B = 9 ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_4_2.DATA_WIDTH_A = 9 ;
    DP8KC pmi_ram_dpXbnonesadr55101024551010241218d42b_0_4_2 (.DIA8(Data[44]), 
        .DIA7(Data[43]), .DIA6(Data[42]), .DIA5(Data[41]), .DIA4(Data[40]), 
        .DIA3(Data[39]), .DIA2(Data[38]), .DIA1(Data[37]), .DIA0(Data[36]), 
        .ADA12(WrAddress[9]), .ADA11(WrAddress[8]), .ADA10(WrAddress[7]), 
        .ADA9(WrAddress[6]), .ADA8(WrAddress[5]), .ADA7(WrAddress[4]), .ADA6(WrAddress[3]), 
        .ADA5(WrAddress[2]), .ADA4(WrAddress[1]), .ADA3(WrAddress[0]), .ADA2(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA0(scuba_vhi), .CEA(WrClockEn), .OCEA(WrClockEn), 
        .CLKA(WrClock), .WEA(WE), .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), 
        .RSTA(Reset), .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB0(scuba_vlo), .ADB12(RdAddress[9]), .ADB11(RdAddress[8]), 
        .ADB10(RdAddress[7]), .ADB9(RdAddress[6]), .ADB8(RdAddress[5]), 
        .ADB7(RdAddress[4]), .ADB6(RdAddress[3]), .ADB5(RdAddress[2]), .ADB4(RdAddress[1]), 
        .ADB3(RdAddress[0]), .ADB2(scuba_vlo), .ADB1(scuba_vlo), .ADB0(scuba_vlo), 
        .CEB(RdClockEn), .OCEB(RdClockEn), .CLKB(RdClock), .WEB(scuba_vlo), 
        .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), 
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), 
        .DOA0(), .DOB8(Q[44]), .DOB7(Q[43]), .DOB6(Q[42]), .DOB5(Q[41]), 
        .DOB4(Q[40]), .DOB3(Q[39]), .DOB2(Q[38]), .DOB1(Q[37]), .DOB0(Q[36]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr55101024551010241218d42b__PMIP__1024__55__55B" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_5_1.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_5_1.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_5_1.CSDECODE_B = "0b000" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_5_1.CSDECODE_A = "0b000" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_5_1.WRITEMODE_B = "NORMAL" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_5_1.WRITEMODE_A = "NORMAL" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_5_1.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_5_1.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_5_1.REGMODE_B = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_5_1.REGMODE_A = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_5_1.DATA_WIDTH_B = 9 ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_5_1.DATA_WIDTH_A = 9 ;
    DP8KC pmi_ram_dpXbnonesadr55101024551010241218d42b_0_5_1 (.DIA8(Data[53]), 
        .DIA7(Data[52]), .DIA6(Data[51]), .DIA5(Data[50]), .DIA4(Data[49]), 
        .DIA3(Data[48]), .DIA2(Data[47]), .DIA1(Data[46]), .DIA0(Data[45]), 
        .ADA12(WrAddress[9]), .ADA11(WrAddress[8]), .ADA10(WrAddress[7]), 
        .ADA9(WrAddress[6]), .ADA8(WrAddress[5]), .ADA7(WrAddress[4]), .ADA6(WrAddress[3]), 
        .ADA5(WrAddress[2]), .ADA4(WrAddress[1]), .ADA3(WrAddress[0]), .ADA2(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA0(scuba_vhi), .CEA(WrClockEn), .OCEA(WrClockEn), 
        .CLKA(WrClock), .WEA(WE), .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), 
        .RSTA(Reset), .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB0(scuba_vlo), .ADB12(RdAddress[9]), .ADB11(RdAddress[8]), 
        .ADB10(RdAddress[7]), .ADB9(RdAddress[6]), .ADB8(RdAddress[5]), 
        .ADB7(RdAddress[4]), .ADB6(RdAddress[3]), .ADB5(RdAddress[2]), .ADB4(RdAddress[1]), 
        .ADB3(RdAddress[0]), .ADB2(scuba_vlo), .ADB1(scuba_vlo), .ADB0(scuba_vlo), 
        .CEB(RdClockEn), .OCEB(RdClockEn), .CLKB(RdClock), .WEB(scuba_vlo), 
        .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), 
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), 
        .DOA0(), .DOB8(Q[53]), .DOB7(Q[52]), .DOB6(Q[51]), .DOB5(Q[50]), 
        .DOB4(Q[49]), .DOB3(Q[48]), .DOB2(Q[47]), .DOB1(Q[46]), .DOB0(Q[45]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr55101024551010241218d42b__PMIP__1024__55__55B" */
             /* synthesis MEM_INIT_FILE="" */;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_6_0.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_6_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_6_0.CSDECODE_B = "0b000" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_6_0.CSDECODE_A = "0b000" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_6_0.WRITEMODE_B = "NORMAL" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_6_0.WRITEMODE_A = "NORMAL" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_6_0.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_6_0.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_6_0.REGMODE_B = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_6_0.REGMODE_A = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_6_0.DATA_WIDTH_B = 9 ;
    defparam pmi_ram_dpXbnonesadr55101024551010241218d42b_0_6_0.DATA_WIDTH_A = 9 ;
    DP8KC pmi_ram_dpXbnonesadr55101024551010241218d42b_0_6_0 (.DIA8(scuba_vlo), 
        .DIA7(scuba_vlo), .DIA6(scuba_vlo), .DIA5(scuba_vlo), .DIA4(scuba_vlo), 
        .DIA3(scuba_vlo), .DIA2(scuba_vlo), .DIA1(scuba_vlo), .DIA0(Data[54]), 
        .ADA12(WrAddress[9]), .ADA11(WrAddress[8]), .ADA10(WrAddress[7]), 
        .ADA9(WrAddress[6]), .ADA8(WrAddress[5]), .ADA7(WrAddress[4]), .ADA6(WrAddress[3]), 
        .ADA5(WrAddress[2]), .ADA4(WrAddress[1]), .ADA3(WrAddress[0]), .ADA2(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA0(scuba_vhi), .CEA(WrClockEn), .OCEA(WrClockEn), 
        .CLKA(WrClock), .WEA(WE), .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), 
        .RSTA(Reset), .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB0(scuba_vlo), .ADB12(RdAddress[9]), .ADB11(RdAddress[8]), 
        .ADB10(RdAddress[7]), .ADB9(RdAddress[6]), .ADB8(RdAddress[5]), 
        .ADB7(RdAddress[4]), .ADB6(RdAddress[3]), .ADB5(RdAddress[2]), .ADB4(RdAddress[1]), 
        .ADB3(RdAddress[0]), .ADB2(scuba_vlo), .ADB1(scuba_vlo), .ADB0(scuba_vlo), 
        .CEB(RdClockEn), .OCEB(RdClockEn), .CLKB(RdClock), .WEB(scuba_vlo), 
        .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), 
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), 
        .DOA0(), .DOB8(), .DOB7(), .DOB6(), .DOB5(), .DOB4(), .DOB3(), .DOB2(), 
        .DOB1(), .DOB0(Q[54]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr55101024551010241218d42b__PMIP__1024__55__55B" */
             /* synthesis MEM_INIT_FILE="" */;



    // exemplar begin
    // exemplar attribute pmi_ram_dpXbnonesadr55101024551010241218d42b_0_0_6 MEM_LPC_FILE pmi_ram_dpXbnonesadr55101024551010241218d42b__PMIP__1024__55__55B
    // exemplar attribute pmi_ram_dpXbnonesadr55101024551010241218d42b_0_0_6 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpXbnonesadr55101024551010241218d42b_0_1_5 MEM_LPC_FILE pmi_ram_dpXbnonesadr55101024551010241218d42b__PMIP__1024__55__55B
    // exemplar attribute pmi_ram_dpXbnonesadr55101024551010241218d42b_0_1_5 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpXbnonesadr55101024551010241218d42b_0_2_4 MEM_LPC_FILE pmi_ram_dpXbnonesadr55101024551010241218d42b__PMIP__1024__55__55B
    // exemplar attribute pmi_ram_dpXbnonesadr55101024551010241218d42b_0_2_4 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpXbnonesadr55101024551010241218d42b_0_3_3 MEM_LPC_FILE pmi_ram_dpXbnonesadr55101024551010241218d42b__PMIP__1024__55__55B
    // exemplar attribute pmi_ram_dpXbnonesadr55101024551010241218d42b_0_3_3 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpXbnonesadr55101024551010241218d42b_0_4_2 MEM_LPC_FILE pmi_ram_dpXbnonesadr55101024551010241218d42b__PMIP__1024__55__55B
    // exemplar attribute pmi_ram_dpXbnonesadr55101024551010241218d42b_0_4_2 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpXbnonesadr55101024551010241218d42b_0_5_1 MEM_LPC_FILE pmi_ram_dpXbnonesadr55101024551010241218d42b__PMIP__1024__55__55B
    // exemplar attribute pmi_ram_dpXbnonesadr55101024551010241218d42b_0_5_1 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpXbnonesadr55101024551010241218d42b_0_6_0 MEM_LPC_FILE pmi_ram_dpXbnonesadr55101024551010241218d42b__PMIP__1024__55__55B
    // exemplar attribute pmi_ram_dpXbnonesadr55101024551010241218d42b_0_6_0 MEM_INIT_FILE 
    // exemplar end

endmodule
