/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 6.5 */
/* C:/lscc/diamond/3.11_x64/ispfpga/bin/nt64/scuba -w -bus_exp 7 -bb -arch xo3c00f -type bram -wp 10 -rp 0011 -data_width 207 -num_rows 256 -rdata_width 207 -read_reg1 outreg -gsr DISABLED -memformat bin -cascade -1 -n pmi_ram_dpXbnonesadr2078256207825611f54fe3 -pmi -lang verilog  */
/* Tue Jan 05 01:35:18 2021 */


`timescale 1 ns / 1 ps
module pmi_ram_dpXbnonesadr2078256207825611f54fe3 (WrAddress, RdAddress, 
    Data, WE, RdClock, RdClockEn, Reset, WrClock, WrClockEn, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [7:0] WrAddress;
    input wire [7:0] RdAddress;
    input wire [206:0] Data;
    input wire WE;
    input wire RdClock;
    input wire RdClockEn;
    input wire Reset;
    input wire WrClock;
    input wire WrClockEn;
    output wire [206:0] Q;

    wire scuba_vhi;
    wire scuba_vlo;

    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_0_11.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_0_11.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_0_11.CSDECODE_R = "0b000" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_0_11.CSDECODE_W = "0b001" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_0_11.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_0_11.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_0_11.REGMODE = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_0_11.DATA_WIDTH_R = 18 ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_0_11.DATA_WIDTH_W = 18 ;
    PDPW8KC pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_0_11 (.DI17(Data[17]), 
        .DI16(Data[16]), .DI15(Data[15]), .DI14(Data[14]), .DI13(Data[13]), 
        .DI12(Data[12]), .DI11(Data[11]), .DI10(Data[10]), .DI9(Data[9]), 
        .DI8(Data[8]), .DI7(Data[7]), .DI6(Data[6]), .DI5(Data[5]), .DI4(Data[4]), 
        .DI3(Data[3]), .DI2(Data[2]), .DI1(Data[1]), .DI0(Data[0]), .ADW8(scuba_vlo), 
        .ADW7(WrAddress[7]), .ADW6(WrAddress[6]), .ADW5(WrAddress[5]), .ADW4(WrAddress[4]), 
        .ADW3(WrAddress[3]), .ADW2(WrAddress[2]), .ADW1(WrAddress[1]), .ADW0(WrAddress[0]), 
        .BE1(scuba_vhi), .BE0(scuba_vhi), .CEW(WrClockEn), .CLKW(WrClock), 
        .CSW2(scuba_vlo), .CSW1(scuba_vlo), .CSW0(WE), .ADR12(scuba_vlo), 
        .ADR11(RdAddress[7]), .ADR10(RdAddress[6]), .ADR9(RdAddress[5]), 
        .ADR8(RdAddress[4]), .ADR7(RdAddress[3]), .ADR6(RdAddress[2]), .ADR5(RdAddress[1]), 
        .ADR4(RdAddress[0]), .ADR3(scuba_vlo), .ADR2(scuba_vlo), .ADR1(scuba_vlo), 
        .ADR0(scuba_vlo), .CER(RdClockEn), .OCER(RdClockEn), .CLKR(RdClock), 
        .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(scuba_vlo), .RST(Reset), 
        .DO17(Q[8]), .DO16(Q[7]), .DO15(Q[6]), .DO14(Q[5]), .DO13(Q[4]), 
        .DO12(Q[3]), .DO11(Q[2]), .DO10(Q[1]), .DO9(Q[0]), .DO8(Q[17]), 
        .DO7(Q[16]), .DO6(Q[15]), .DO5(Q[14]), .DO4(Q[13]), .DO3(Q[12]), 
        .DO2(Q[11]), .DO1(Q[10]), .DO0(Q[9]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_1_10.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_1_10.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_1_10.CSDECODE_R = "0b000" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_1_10.CSDECODE_W = "0b001" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_1_10.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_1_10.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_1_10.REGMODE = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_1_10.DATA_WIDTH_R = 18 ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_1_10.DATA_WIDTH_W = 18 ;
    PDPW8KC pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_1_10 (.DI17(Data[35]), 
        .DI16(Data[34]), .DI15(Data[33]), .DI14(Data[32]), .DI13(Data[31]), 
        .DI12(Data[30]), .DI11(Data[29]), .DI10(Data[28]), .DI9(Data[27]), 
        .DI8(Data[26]), .DI7(Data[25]), .DI6(Data[24]), .DI5(Data[23]), 
        .DI4(Data[22]), .DI3(Data[21]), .DI2(Data[20]), .DI1(Data[19]), 
        .DI0(Data[18]), .ADW8(scuba_vlo), .ADW7(WrAddress[7]), .ADW6(WrAddress[6]), 
        .ADW5(WrAddress[5]), .ADW4(WrAddress[4]), .ADW3(WrAddress[3]), .ADW2(WrAddress[2]), 
        .ADW1(WrAddress[1]), .ADW0(WrAddress[0]), .BE1(scuba_vhi), .BE0(scuba_vhi), 
        .CEW(WrClockEn), .CLKW(WrClock), .CSW2(scuba_vlo), .CSW1(scuba_vlo), 
        .CSW0(WE), .ADR12(scuba_vlo), .ADR11(RdAddress[7]), .ADR10(RdAddress[6]), 
        .ADR9(RdAddress[5]), .ADR8(RdAddress[4]), .ADR7(RdAddress[3]), .ADR6(RdAddress[2]), 
        .ADR5(RdAddress[1]), .ADR4(RdAddress[0]), .ADR3(scuba_vlo), .ADR2(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR0(scuba_vlo), .CER(RdClockEn), .OCER(RdClockEn), 
        .CLKR(RdClock), .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(scuba_vlo), 
        .RST(Reset), .DO17(Q[26]), .DO16(Q[25]), .DO15(Q[24]), .DO14(Q[23]), 
        .DO13(Q[22]), .DO12(Q[21]), .DO11(Q[20]), .DO10(Q[19]), .DO9(Q[18]), 
        .DO8(Q[35]), .DO7(Q[34]), .DO6(Q[33]), .DO5(Q[32]), .DO4(Q[31]), 
        .DO3(Q[30]), .DO2(Q[29]), .DO1(Q[28]), .DO0(Q[27]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_2_9.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_2_9.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_2_9.CSDECODE_R = "0b000" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_2_9.CSDECODE_W = "0b001" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_2_9.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_2_9.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_2_9.REGMODE = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_2_9.DATA_WIDTH_R = 18 ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_2_9.DATA_WIDTH_W = 18 ;
    PDPW8KC pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_2_9 (.DI17(Data[53]), 
        .DI16(Data[52]), .DI15(Data[51]), .DI14(Data[50]), .DI13(Data[49]), 
        .DI12(Data[48]), .DI11(Data[47]), .DI10(Data[46]), .DI9(Data[45]), 
        .DI8(Data[44]), .DI7(Data[43]), .DI6(Data[42]), .DI5(Data[41]), 
        .DI4(Data[40]), .DI3(Data[39]), .DI2(Data[38]), .DI1(Data[37]), 
        .DI0(Data[36]), .ADW8(scuba_vlo), .ADW7(WrAddress[7]), .ADW6(WrAddress[6]), 
        .ADW5(WrAddress[5]), .ADW4(WrAddress[4]), .ADW3(WrAddress[3]), .ADW2(WrAddress[2]), 
        .ADW1(WrAddress[1]), .ADW0(WrAddress[0]), .BE1(scuba_vhi), .BE0(scuba_vhi), 
        .CEW(WrClockEn), .CLKW(WrClock), .CSW2(scuba_vlo), .CSW1(scuba_vlo), 
        .CSW0(WE), .ADR12(scuba_vlo), .ADR11(RdAddress[7]), .ADR10(RdAddress[6]), 
        .ADR9(RdAddress[5]), .ADR8(RdAddress[4]), .ADR7(RdAddress[3]), .ADR6(RdAddress[2]), 
        .ADR5(RdAddress[1]), .ADR4(RdAddress[0]), .ADR3(scuba_vlo), .ADR2(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR0(scuba_vlo), .CER(RdClockEn), .OCER(RdClockEn), 
        .CLKR(RdClock), .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(scuba_vlo), 
        .RST(Reset), .DO17(Q[44]), .DO16(Q[43]), .DO15(Q[42]), .DO14(Q[41]), 
        .DO13(Q[40]), .DO12(Q[39]), .DO11(Q[38]), .DO10(Q[37]), .DO9(Q[36]), 
        .DO8(Q[53]), .DO7(Q[52]), .DO6(Q[51]), .DO5(Q[50]), .DO4(Q[49]), 
        .DO3(Q[48]), .DO2(Q[47]), .DO1(Q[46]), .DO0(Q[45]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_3_8.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_3_8.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_3_8.CSDECODE_R = "0b000" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_3_8.CSDECODE_W = "0b001" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_3_8.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_3_8.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_3_8.REGMODE = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_3_8.DATA_WIDTH_R = 18 ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_3_8.DATA_WIDTH_W = 18 ;
    PDPW8KC pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_3_8 (.DI17(Data[71]), 
        .DI16(Data[70]), .DI15(Data[69]), .DI14(Data[68]), .DI13(Data[67]), 
        .DI12(Data[66]), .DI11(Data[65]), .DI10(Data[64]), .DI9(Data[63]), 
        .DI8(Data[62]), .DI7(Data[61]), .DI6(Data[60]), .DI5(Data[59]), 
        .DI4(Data[58]), .DI3(Data[57]), .DI2(Data[56]), .DI1(Data[55]), 
        .DI0(Data[54]), .ADW8(scuba_vlo), .ADW7(WrAddress[7]), .ADW6(WrAddress[6]), 
        .ADW5(WrAddress[5]), .ADW4(WrAddress[4]), .ADW3(WrAddress[3]), .ADW2(WrAddress[2]), 
        .ADW1(WrAddress[1]), .ADW0(WrAddress[0]), .BE1(scuba_vhi), .BE0(scuba_vhi), 
        .CEW(WrClockEn), .CLKW(WrClock), .CSW2(scuba_vlo), .CSW1(scuba_vlo), 
        .CSW0(WE), .ADR12(scuba_vlo), .ADR11(RdAddress[7]), .ADR10(RdAddress[6]), 
        .ADR9(RdAddress[5]), .ADR8(RdAddress[4]), .ADR7(RdAddress[3]), .ADR6(RdAddress[2]), 
        .ADR5(RdAddress[1]), .ADR4(RdAddress[0]), .ADR3(scuba_vlo), .ADR2(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR0(scuba_vlo), .CER(RdClockEn), .OCER(RdClockEn), 
        .CLKR(RdClock), .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(scuba_vlo), 
        .RST(Reset), .DO17(Q[62]), .DO16(Q[61]), .DO15(Q[60]), .DO14(Q[59]), 
        .DO13(Q[58]), .DO12(Q[57]), .DO11(Q[56]), .DO10(Q[55]), .DO9(Q[54]), 
        .DO8(Q[71]), .DO7(Q[70]), .DO6(Q[69]), .DO5(Q[68]), .DO4(Q[67]), 
        .DO3(Q[66]), .DO2(Q[65]), .DO1(Q[64]), .DO0(Q[63]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_4_7.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_4_7.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_4_7.CSDECODE_R = "0b000" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_4_7.CSDECODE_W = "0b001" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_4_7.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_4_7.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_4_7.REGMODE = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_4_7.DATA_WIDTH_R = 18 ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_4_7.DATA_WIDTH_W = 18 ;
    PDPW8KC pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_4_7 (.DI17(Data[89]), 
        .DI16(Data[88]), .DI15(Data[87]), .DI14(Data[86]), .DI13(Data[85]), 
        .DI12(Data[84]), .DI11(Data[83]), .DI10(Data[82]), .DI9(Data[81]), 
        .DI8(Data[80]), .DI7(Data[79]), .DI6(Data[78]), .DI5(Data[77]), 
        .DI4(Data[76]), .DI3(Data[75]), .DI2(Data[74]), .DI1(Data[73]), 
        .DI0(Data[72]), .ADW8(scuba_vlo), .ADW7(WrAddress[7]), .ADW6(WrAddress[6]), 
        .ADW5(WrAddress[5]), .ADW4(WrAddress[4]), .ADW3(WrAddress[3]), .ADW2(WrAddress[2]), 
        .ADW1(WrAddress[1]), .ADW0(WrAddress[0]), .BE1(scuba_vhi), .BE0(scuba_vhi), 
        .CEW(WrClockEn), .CLKW(WrClock), .CSW2(scuba_vlo), .CSW1(scuba_vlo), 
        .CSW0(WE), .ADR12(scuba_vlo), .ADR11(RdAddress[7]), .ADR10(RdAddress[6]), 
        .ADR9(RdAddress[5]), .ADR8(RdAddress[4]), .ADR7(RdAddress[3]), .ADR6(RdAddress[2]), 
        .ADR5(RdAddress[1]), .ADR4(RdAddress[0]), .ADR3(scuba_vlo), .ADR2(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR0(scuba_vlo), .CER(RdClockEn), .OCER(RdClockEn), 
        .CLKR(RdClock), .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(scuba_vlo), 
        .RST(Reset), .DO17(Q[80]), .DO16(Q[79]), .DO15(Q[78]), .DO14(Q[77]), 
        .DO13(Q[76]), .DO12(Q[75]), .DO11(Q[74]), .DO10(Q[73]), .DO9(Q[72]), 
        .DO8(Q[89]), .DO7(Q[88]), .DO6(Q[87]), .DO5(Q[86]), .DO4(Q[85]), 
        .DO3(Q[84]), .DO2(Q[83]), .DO1(Q[82]), .DO0(Q[81]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_5_6.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_5_6.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_5_6.CSDECODE_R = "0b000" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_5_6.CSDECODE_W = "0b001" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_5_6.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_5_6.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_5_6.REGMODE = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_5_6.DATA_WIDTH_R = 18 ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_5_6.DATA_WIDTH_W = 18 ;
    PDPW8KC pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_5_6 (.DI17(Data[107]), 
        .DI16(Data[106]), .DI15(Data[105]), .DI14(Data[104]), .DI13(Data[103]), 
        .DI12(Data[102]), .DI11(Data[101]), .DI10(Data[100]), .DI9(Data[99]), 
        .DI8(Data[98]), .DI7(Data[97]), .DI6(Data[96]), .DI5(Data[95]), 
        .DI4(Data[94]), .DI3(Data[93]), .DI2(Data[92]), .DI1(Data[91]), 
        .DI0(Data[90]), .ADW8(scuba_vlo), .ADW7(WrAddress[7]), .ADW6(WrAddress[6]), 
        .ADW5(WrAddress[5]), .ADW4(WrAddress[4]), .ADW3(WrAddress[3]), .ADW2(WrAddress[2]), 
        .ADW1(WrAddress[1]), .ADW0(WrAddress[0]), .BE1(scuba_vhi), .BE0(scuba_vhi), 
        .CEW(WrClockEn), .CLKW(WrClock), .CSW2(scuba_vlo), .CSW1(scuba_vlo), 
        .CSW0(WE), .ADR12(scuba_vlo), .ADR11(RdAddress[7]), .ADR10(RdAddress[6]), 
        .ADR9(RdAddress[5]), .ADR8(RdAddress[4]), .ADR7(RdAddress[3]), .ADR6(RdAddress[2]), 
        .ADR5(RdAddress[1]), .ADR4(RdAddress[0]), .ADR3(scuba_vlo), .ADR2(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR0(scuba_vlo), .CER(RdClockEn), .OCER(RdClockEn), 
        .CLKR(RdClock), .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(scuba_vlo), 
        .RST(Reset), .DO17(Q[98]), .DO16(Q[97]), .DO15(Q[96]), .DO14(Q[95]), 
        .DO13(Q[94]), .DO12(Q[93]), .DO11(Q[92]), .DO10(Q[91]), .DO9(Q[90]), 
        .DO8(Q[107]), .DO7(Q[106]), .DO6(Q[105]), .DO5(Q[104]), .DO4(Q[103]), 
        .DO3(Q[102]), .DO2(Q[101]), .DO1(Q[100]), .DO0(Q[99]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_6_5.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_6_5.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_6_5.CSDECODE_R = "0b000" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_6_5.CSDECODE_W = "0b001" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_6_5.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_6_5.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_6_5.REGMODE = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_6_5.DATA_WIDTH_R = 18 ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_6_5.DATA_WIDTH_W = 18 ;
    PDPW8KC pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_6_5 (.DI17(Data[125]), 
        .DI16(Data[124]), .DI15(Data[123]), .DI14(Data[122]), .DI13(Data[121]), 
        .DI12(Data[120]), .DI11(Data[119]), .DI10(Data[118]), .DI9(Data[117]), 
        .DI8(Data[116]), .DI7(Data[115]), .DI6(Data[114]), .DI5(Data[113]), 
        .DI4(Data[112]), .DI3(Data[111]), .DI2(Data[110]), .DI1(Data[109]), 
        .DI0(Data[108]), .ADW8(scuba_vlo), .ADW7(WrAddress[7]), .ADW6(WrAddress[6]), 
        .ADW5(WrAddress[5]), .ADW4(WrAddress[4]), .ADW3(WrAddress[3]), .ADW2(WrAddress[2]), 
        .ADW1(WrAddress[1]), .ADW0(WrAddress[0]), .BE1(scuba_vhi), .BE0(scuba_vhi), 
        .CEW(WrClockEn), .CLKW(WrClock), .CSW2(scuba_vlo), .CSW1(scuba_vlo), 
        .CSW0(WE), .ADR12(scuba_vlo), .ADR11(RdAddress[7]), .ADR10(RdAddress[6]), 
        .ADR9(RdAddress[5]), .ADR8(RdAddress[4]), .ADR7(RdAddress[3]), .ADR6(RdAddress[2]), 
        .ADR5(RdAddress[1]), .ADR4(RdAddress[0]), .ADR3(scuba_vlo), .ADR2(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR0(scuba_vlo), .CER(RdClockEn), .OCER(RdClockEn), 
        .CLKR(RdClock), .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(scuba_vlo), 
        .RST(Reset), .DO17(Q[116]), .DO16(Q[115]), .DO15(Q[114]), .DO14(Q[113]), 
        .DO13(Q[112]), .DO12(Q[111]), .DO11(Q[110]), .DO10(Q[109]), .DO9(Q[108]), 
        .DO8(Q[125]), .DO7(Q[124]), .DO6(Q[123]), .DO5(Q[122]), .DO4(Q[121]), 
        .DO3(Q[120]), .DO2(Q[119]), .DO1(Q[118]), .DO0(Q[117]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_7_4.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_7_4.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_7_4.CSDECODE_R = "0b000" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_7_4.CSDECODE_W = "0b001" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_7_4.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_7_4.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_7_4.REGMODE = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_7_4.DATA_WIDTH_R = 18 ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_7_4.DATA_WIDTH_W = 18 ;
    PDPW8KC pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_7_4 (.DI17(Data[143]), 
        .DI16(Data[142]), .DI15(Data[141]), .DI14(Data[140]), .DI13(Data[139]), 
        .DI12(Data[138]), .DI11(Data[137]), .DI10(Data[136]), .DI9(Data[135]), 
        .DI8(Data[134]), .DI7(Data[133]), .DI6(Data[132]), .DI5(Data[131]), 
        .DI4(Data[130]), .DI3(Data[129]), .DI2(Data[128]), .DI1(Data[127]), 
        .DI0(Data[126]), .ADW8(scuba_vlo), .ADW7(WrAddress[7]), .ADW6(WrAddress[6]), 
        .ADW5(WrAddress[5]), .ADW4(WrAddress[4]), .ADW3(WrAddress[3]), .ADW2(WrAddress[2]), 
        .ADW1(WrAddress[1]), .ADW0(WrAddress[0]), .BE1(scuba_vhi), .BE0(scuba_vhi), 
        .CEW(WrClockEn), .CLKW(WrClock), .CSW2(scuba_vlo), .CSW1(scuba_vlo), 
        .CSW0(WE), .ADR12(scuba_vlo), .ADR11(RdAddress[7]), .ADR10(RdAddress[6]), 
        .ADR9(RdAddress[5]), .ADR8(RdAddress[4]), .ADR7(RdAddress[3]), .ADR6(RdAddress[2]), 
        .ADR5(RdAddress[1]), .ADR4(RdAddress[0]), .ADR3(scuba_vlo), .ADR2(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR0(scuba_vlo), .CER(RdClockEn), .OCER(RdClockEn), 
        .CLKR(RdClock), .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(scuba_vlo), 
        .RST(Reset), .DO17(Q[134]), .DO16(Q[133]), .DO15(Q[132]), .DO14(Q[131]), 
        .DO13(Q[130]), .DO12(Q[129]), .DO11(Q[128]), .DO10(Q[127]), .DO9(Q[126]), 
        .DO8(Q[143]), .DO7(Q[142]), .DO6(Q[141]), .DO5(Q[140]), .DO4(Q[139]), 
        .DO3(Q[138]), .DO2(Q[137]), .DO1(Q[136]), .DO0(Q[135]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_8_3.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_8_3.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_8_3.CSDECODE_R = "0b000" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_8_3.CSDECODE_W = "0b001" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_8_3.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_8_3.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_8_3.REGMODE = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_8_3.DATA_WIDTH_R = 18 ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_8_3.DATA_WIDTH_W = 18 ;
    PDPW8KC pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_8_3 (.DI17(Data[161]), 
        .DI16(Data[160]), .DI15(Data[159]), .DI14(Data[158]), .DI13(Data[157]), 
        .DI12(Data[156]), .DI11(Data[155]), .DI10(Data[154]), .DI9(Data[153]), 
        .DI8(Data[152]), .DI7(Data[151]), .DI6(Data[150]), .DI5(Data[149]), 
        .DI4(Data[148]), .DI3(Data[147]), .DI2(Data[146]), .DI1(Data[145]), 
        .DI0(Data[144]), .ADW8(scuba_vlo), .ADW7(WrAddress[7]), .ADW6(WrAddress[6]), 
        .ADW5(WrAddress[5]), .ADW4(WrAddress[4]), .ADW3(WrAddress[3]), .ADW2(WrAddress[2]), 
        .ADW1(WrAddress[1]), .ADW0(WrAddress[0]), .BE1(scuba_vhi), .BE0(scuba_vhi), 
        .CEW(WrClockEn), .CLKW(WrClock), .CSW2(scuba_vlo), .CSW1(scuba_vlo), 
        .CSW0(WE), .ADR12(scuba_vlo), .ADR11(RdAddress[7]), .ADR10(RdAddress[6]), 
        .ADR9(RdAddress[5]), .ADR8(RdAddress[4]), .ADR7(RdAddress[3]), .ADR6(RdAddress[2]), 
        .ADR5(RdAddress[1]), .ADR4(RdAddress[0]), .ADR3(scuba_vlo), .ADR2(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR0(scuba_vlo), .CER(RdClockEn), .OCER(RdClockEn), 
        .CLKR(RdClock), .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(scuba_vlo), 
        .RST(Reset), .DO17(Q[152]), .DO16(Q[151]), .DO15(Q[150]), .DO14(Q[149]), 
        .DO13(Q[148]), .DO12(Q[147]), .DO11(Q[146]), .DO10(Q[145]), .DO9(Q[144]), 
        .DO8(Q[161]), .DO7(Q[160]), .DO6(Q[159]), .DO5(Q[158]), .DO4(Q[157]), 
        .DO3(Q[156]), .DO2(Q[155]), .DO1(Q[154]), .DO0(Q[153]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_9_2.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_9_2.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_9_2.CSDECODE_R = "0b000" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_9_2.CSDECODE_W = "0b001" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_9_2.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_9_2.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_9_2.REGMODE = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_9_2.DATA_WIDTH_R = 18 ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_9_2.DATA_WIDTH_W = 18 ;
    PDPW8KC pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_9_2 (.DI17(Data[179]), 
        .DI16(Data[178]), .DI15(Data[177]), .DI14(Data[176]), .DI13(Data[175]), 
        .DI12(Data[174]), .DI11(Data[173]), .DI10(Data[172]), .DI9(Data[171]), 
        .DI8(Data[170]), .DI7(Data[169]), .DI6(Data[168]), .DI5(Data[167]), 
        .DI4(Data[166]), .DI3(Data[165]), .DI2(Data[164]), .DI1(Data[163]), 
        .DI0(Data[162]), .ADW8(scuba_vlo), .ADW7(WrAddress[7]), .ADW6(WrAddress[6]), 
        .ADW5(WrAddress[5]), .ADW4(WrAddress[4]), .ADW3(WrAddress[3]), .ADW2(WrAddress[2]), 
        .ADW1(WrAddress[1]), .ADW0(WrAddress[0]), .BE1(scuba_vhi), .BE0(scuba_vhi), 
        .CEW(WrClockEn), .CLKW(WrClock), .CSW2(scuba_vlo), .CSW1(scuba_vlo), 
        .CSW0(WE), .ADR12(scuba_vlo), .ADR11(RdAddress[7]), .ADR10(RdAddress[6]), 
        .ADR9(RdAddress[5]), .ADR8(RdAddress[4]), .ADR7(RdAddress[3]), .ADR6(RdAddress[2]), 
        .ADR5(RdAddress[1]), .ADR4(RdAddress[0]), .ADR3(scuba_vlo), .ADR2(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR0(scuba_vlo), .CER(RdClockEn), .OCER(RdClockEn), 
        .CLKR(RdClock), .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(scuba_vlo), 
        .RST(Reset), .DO17(Q[170]), .DO16(Q[169]), .DO15(Q[168]), .DO14(Q[167]), 
        .DO13(Q[166]), .DO12(Q[165]), .DO11(Q[164]), .DO10(Q[163]), .DO9(Q[162]), 
        .DO8(Q[179]), .DO7(Q[178]), .DO6(Q[177]), .DO5(Q[176]), .DO4(Q[175]), 
        .DO3(Q[174]), .DO2(Q[173]), .DO1(Q[172]), .DO0(Q[171]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_10_1.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_10_1.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_10_1.CSDECODE_R = "0b000" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_10_1.CSDECODE_W = "0b001" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_10_1.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_10_1.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_10_1.REGMODE = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_10_1.DATA_WIDTH_R = 18 ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_10_1.DATA_WIDTH_W = 18 ;
    PDPW8KC pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_10_1 (.DI17(Data[197]), 
        .DI16(Data[196]), .DI15(Data[195]), .DI14(Data[194]), .DI13(Data[193]), 
        .DI12(Data[192]), .DI11(Data[191]), .DI10(Data[190]), .DI9(Data[189]), 
        .DI8(Data[188]), .DI7(Data[187]), .DI6(Data[186]), .DI5(Data[185]), 
        .DI4(Data[184]), .DI3(Data[183]), .DI2(Data[182]), .DI1(Data[181]), 
        .DI0(Data[180]), .ADW8(scuba_vlo), .ADW7(WrAddress[7]), .ADW6(WrAddress[6]), 
        .ADW5(WrAddress[5]), .ADW4(WrAddress[4]), .ADW3(WrAddress[3]), .ADW2(WrAddress[2]), 
        .ADW1(WrAddress[1]), .ADW0(WrAddress[0]), .BE1(scuba_vhi), .BE0(scuba_vhi), 
        .CEW(WrClockEn), .CLKW(WrClock), .CSW2(scuba_vlo), .CSW1(scuba_vlo), 
        .CSW0(WE), .ADR12(scuba_vlo), .ADR11(RdAddress[7]), .ADR10(RdAddress[6]), 
        .ADR9(RdAddress[5]), .ADR8(RdAddress[4]), .ADR7(RdAddress[3]), .ADR6(RdAddress[2]), 
        .ADR5(RdAddress[1]), .ADR4(RdAddress[0]), .ADR3(scuba_vlo), .ADR2(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR0(scuba_vlo), .CER(RdClockEn), .OCER(RdClockEn), 
        .CLKR(RdClock), .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(scuba_vlo), 
        .RST(Reset), .DO17(Q[188]), .DO16(Q[187]), .DO15(Q[186]), .DO14(Q[185]), 
        .DO13(Q[184]), .DO12(Q[183]), .DO11(Q[182]), .DO10(Q[181]), .DO9(Q[180]), 
        .DO8(Q[197]), .DO7(Q[196]), .DO6(Q[195]), .DO5(Q[194]), .DO4(Q[193]), 
        .DO3(Q[192]), .DO2(Q[191]), .DO1(Q[190]), .DO0(Q[189]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B" */
             /* synthesis MEM_INIT_FILE="" */;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_11_0.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_11_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_11_0.CSDECODE_R = "0b000" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_11_0.CSDECODE_W = "0b001" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_11_0.GSR = "ENABLED" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_11_0.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_11_0.REGMODE = "OUTREG" ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_11_0.DATA_WIDTH_R = 18 ;
    defparam pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_11_0.DATA_WIDTH_W = 18 ;
    PDPW8KC pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_11_0 (.DI17(scuba_vlo), 
        .DI16(scuba_vlo), .DI15(scuba_vlo), .DI14(scuba_vlo), .DI13(scuba_vlo), 
        .DI12(scuba_vlo), .DI11(scuba_vlo), .DI10(scuba_vlo), .DI9(scuba_vlo), 
        .DI8(Data[206]), .DI7(Data[205]), .DI6(Data[204]), .DI5(Data[203]), 
        .DI4(Data[202]), .DI3(Data[201]), .DI2(Data[200]), .DI1(Data[199]), 
        .DI0(Data[198]), .ADW8(scuba_vlo), .ADW7(WrAddress[7]), .ADW6(WrAddress[6]), 
        .ADW5(WrAddress[5]), .ADW4(WrAddress[4]), .ADW3(WrAddress[3]), .ADW2(WrAddress[2]), 
        .ADW1(WrAddress[1]), .ADW0(WrAddress[0]), .BE1(scuba_vhi), .BE0(scuba_vhi), 
        .CEW(WrClockEn), .CLKW(WrClock), .CSW2(scuba_vlo), .CSW1(scuba_vlo), 
        .CSW0(WE), .ADR12(scuba_vlo), .ADR11(RdAddress[7]), .ADR10(RdAddress[6]), 
        .ADR9(RdAddress[5]), .ADR8(RdAddress[4]), .ADR7(RdAddress[3]), .ADR6(RdAddress[2]), 
        .ADR5(RdAddress[1]), .ADR4(RdAddress[0]), .ADR3(scuba_vlo), .ADR2(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR0(scuba_vlo), .CER(RdClockEn), .OCER(RdClockEn), 
        .CLKR(RdClock), .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(scuba_vlo), 
        .RST(Reset), .DO17(Q[206]), .DO16(Q[205]), .DO15(Q[204]), .DO14(Q[203]), 
        .DO13(Q[202]), .DO12(Q[201]), .DO11(Q[200]), .DO10(Q[199]), .DO9(Q[198]), 
        .DO8(), .DO7(), .DO6(), .DO5(), .DO4(), .DO3(), .DO2(), .DO1(), 
        .DO0())
             /* synthesis MEM_LPC_FILE="pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B" */
             /* synthesis MEM_INIT_FILE="" */;



    // exemplar begin
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_0_11 MEM_LPC_FILE pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_0_11 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_1_10 MEM_LPC_FILE pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_1_10 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_2_9 MEM_LPC_FILE pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_2_9 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_3_8 MEM_LPC_FILE pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_3_8 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_4_7 MEM_LPC_FILE pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_4_7 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_5_6 MEM_LPC_FILE pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_5_6 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_6_5 MEM_LPC_FILE pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_6_5 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_7_4 MEM_LPC_FILE pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_7_4 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_8_3 MEM_LPC_FILE pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_8_3 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_9_2 MEM_LPC_FILE pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_9_2 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_10_1 MEM_LPC_FILE pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_10_1 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_11_0 MEM_LPC_FILE pmi_ram_dpXbnonesadr2078256207825611f54fe3__PMIP__256__207__207B
    // exemplar attribute pmi_ram_dpXbnonesadr2078256207825611f54fe3_0_11_0 MEM_INIT_FILE 
    // exemplar end

endmodule
